### ISSUE TITLE
Possible results print typo

### ISSUE THREAD

**Issue by heathhenley** [WomensWorldBanking/Algorithmic_Bias#1]
If I understand correctly, in the results summary part `A. Are we violating predictive parity fairness?`, I think that the second `PPV_M` in the print statement below should be `PPV_F`:

``` python
print('Creditworthy male loan applicants have', round(float(np.array(df_at_Opt_Thereshold_M['PPV_M'] * 100)), 1), 'chance of receiving loan,')
print('while creditworthy female loan applicants have', round(float(np.array(df_at_Opt_Thereshold_M['PPV_M'] * 100)), 1), 'chance of receiving loan') 
```
so it seems the programmer my have also demonstrated some implicit gender bias when printing their results :)

**Comment by WomensWorldBanking** [comment]
Dear Heath,
Thank you very much for your feedback. I edited the typo.  
Again, I do appreciate it a lot. 
Cheers,
Mehrdad
